#shaderType
diagnostic_surface_shader
#shaderName
diagnostic_surface_shader0
#Name|Details|Type|IsOutput|Defaults|ArraySizes
mode|uniform|string|0|"ambient_occlusion"|-1
#mode|uniform|string|0|"assembly_instances"|-1
#mode|uniform|string|0|"barycentric"|-1
#mode|uniform|string|0|"bitangent"|-1
#mode|uniform|string|0|"coverage"|-1
#mode|uniform|string|0|"depth"|-1
#mode|uniform|string|0|"geometric_normal"|-1
#mode|uniform|string|0|"materials"|-1
#mode|uniform|string|0|"object_instances"|-1
#mode|uniform|string|0|"original_shading_normal"|-1
#mode|uniform|string|0|"regions"|-1
#mode|uniform|string|0|"shading_normal"|-1
#mode|uniform|string|0|"sides"|-1
#mode|uniform|string|0|"tangent"|-1
#mode|uniform|string|0|"triangles"|-1
#mode|uniform|string|0|"uv"|-1
#mode|uniform|string|0|"wireframe"|-1