#shaderType
surface
#shaderName
as_shader
#Name|Details|Type|IsOutput|Defaults|ArraySizes
bsdf_model|uniform|string|0|"lambertian_brdf"|-1
lambertian_brdf_reflectance|uniform|color|0|<<1.0,1.0,1.0>>|-1
lambertian_brdf_reflectance_multiplier|uniform|color|0|<<1.0,1.0,1.0>>|-1

edf_model|uniform|string|0|"diffuse_edf"|-1
diffuse_edf_exitance|uniform|color|0|<<1.0,1.0,1.0>>|-1
diffuse_edf_exitance_multiplier|uniform|color|0|<<1.0,1.0,1.0>>|-1

surface_shader_model|uniform|string|0|"diagnostic_surface_shader"|-1
diagnostic_surface_shader_mode|uniform|string|0|"ambient_occlusion"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"assembly_instances"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"barycentric"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"bitangent"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"coverage"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"depth"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"geometric_normal"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"materials"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"object_instances"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"original_shading_normal"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"regions"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"shading_normal"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"sides"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"tangent"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"triangles"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"uv"|-1
#diagnostic_surface_shader_mode|uniform|string|0|"wireframe"|-1