print "This is $ER_SHADER_USER/src/erChecker/userSetup.mel\n";

string $erSHADER_user_DIR = getenv("ER_SHADER_USER");
if( $erSHADER_user_DIR == "" )
{
    error("environment variable <ER_SHADER_USER> is not set in Maya.env");
} else {
    eval( "source \"" + $erSHADER_user_DIR + "/src/erChecker/AEerCheckerTemplate.mel\"" );
}
//
global proc int liquidAssignUserShaderToSelected_elvishray_erChecker(string $node)
{
	liqPushIdent();	
	liqAElog("liquidAssignUserShaderToSelected_elvishray_erChecker("+$node+")");
	


	liqPopIdent();
	return 1;
}
//
global proc liquidBuildHypergraphNodePopupMenuItems_erChecker( string $node )
{
	liqPushIdent();
	liqlog("liquidBuildHypergraphNodePopupMenuItems_erChecker("+$node+")");
	liqPopIdent();
}