//### SCENE BEGIN ###
//    Generated by Liquid v2.3.5 (buildtime= 0:29:12.04)
//    Scene : E:/MyDocuments/maya/projects/default/as_test_lambert_btdf
//    User  : yaoyansi
//    Time  : Wed Sep 12 22:16:49 2012


//############################### option #
// maya settings: focal=35, aperture = 36, aspect=1.33333
//Depth of Field on camera "|persp|perspShape" is turned off in Maya

//############################### camera #
//----------------------------------camera instance: currentJob.camera[0].name
ei_shader("lambert4");
ei_shader_param_string("desc", "maya_lambert_transparent");
ei_shader_param_vector("Cs", 1, 0, 0);
ei_shader_param_vector("transparency", 0.643168, 0.643168, 0.643168);
ei_shader_param_vector("ambientColor", 0, 0, 0);
ei_shader_param_vector("incandescence", 0, 0, 0);
ei_shader_param_scalar("diffusion", 0.8);
ei_shader_param_vector("outColor", 0, 0, 0);
ei_shader_param_vector("outTransparency", 0.643168, 0.643168, 0.643168);
ei_end_shader();

ei_material("lambert4SG");
ei_add_surface("lambert4");
ei_end_material();
ei_shader("lambert1");
ei_shader_param_string("desc", "maya_lambert_transparent");
ei_shader_param_vector("Cs", 0.5, 0.5, 0.5);
ei_shader_param_vector("transparency", 0, 0, 0);
ei_shader_param_vector("ambientColor", 0, 0, 0);
ei_shader_param_vector("incandescence", 0, 0, 0);
ei_shader_param_scalar("diffusion", 0.8);
ei_shader_param_vector("outColor", 0, 0, 0);
ei_shader_param_vector("outTransparency", 0, 0, 0);
ei_end_shader();

ei_material("initialShadingGroup");
ei_add_surface("lambert1");
ei_end_material();

//worldPrologue

// Renderer::exportLight("_pointLight1_pointLightShape1");

// Renderer::exportPointLight()

// Renderer::exportOneGeometry_Mesh(|pPlane7|pPlaneShape4,0,0)

//############################### mesh #
//shape full path name=|pPlane7|pPlaneShape4

// Renderer::exportOneGeometry_Mesh(|pCube1|pCubeShape1,0,0)

//############################### mesh #
//shape full path name=|pCube1|pCubeShape1

// Renderer::exportOneGeometry_Mesh(|pCube2|pCubeShape2,0,0)

//############################### mesh #
//shape full path name=|pCube2|pCubeShape2
//--------------------------
//ribNode->name=|pPlane7|pPlaneShape4
//ribNode's transform node=|pPlane7
//ribNode->object(0)->getDataPtr()->getFullPathName()=|pPlane7|pPlaneShape4
//shape name=|pPlane7|pPlaneShape4
//shape full path name=|pPlane7|pPlaneShape4
//ribNode->doDef=205, ribNode->doMotion=205
{//light group(light-link group)
//
//--------------------------
//ribNode->name=|pCube1|pCubeShape1
//ribNode's transform node=|pCube1
//ribNode->object(0)->getDataPtr()->getFullPathName()=|pCube1|pCubeShape1
//shape name=|pCube1|pCubeShape1
//shape full path name=|pCube1|pCubeShape1
//ribNode->doDef=205, ribNode->doMotion=205
{//light group(light-link group)
//
//--------------------------
//ribNode->name=|pCube2|pCubeShape2
//ribNode's transform node=|pCube2
//ribNode->object(0)->getDataPtr()->getFullPathName()=|pCube2|pCubeShape2
//shape name=|pCube2|pCubeShape2
//shape full path name=|pCube2|pCubeShape2
//ribNode->doDef=205, ribNode->doMotion=205
{//light group(light-link group)
//

//Renderer::worldEpilogue()
//image width/height=400,300
//min[0,0], max[32,32]
//updatePixels[//image width/height=0400,,31300, 
300,//min[26932],
0], max[64,32]
//updatePixels[32,63, 300,269]
//image width/height=400,300
//min[32,32], max[64,64]
//updatePixels[32,63, 268,237]
//image width/height=400,300
//min[0,32], max[32,64]
//updatePixels[0,31, 268,237]
//image width/height=400,300
//min[0//image width/height=,40064,], max[30032
,96//min[]0
,96//updatePixels[], max[032,,31128, ]236
,205//updatePixels[]0
,31, 204,173]
//image width/height=400,300
//min[32,96], max[64,128]
//updatePixels[32,63, 204,173]
//image width/height=400,300
//min[32,64], max[64,96]
//updatePixels[32,63, 236,205]
//image width/height=400,300
//min[64,64], max[96,96]
//updatePixels[64,95, 236,205]
//image width/height=400,300
//min[64,96], max[96,128]
//updatePixels[64,95, 204,173]
//image width/height=400,300
//min[96,64], max[128,96]
//updatePixels[96,127, 236,205]
//image width/height=400,300
//min[96,32], max[128,64]
//updatePixels[96,127, 268,237]
//image width/height=400,300
//min[64,32], max[96,64]
//updatePixels[64,95, 268,237]
//image width/height=400,300
//min[64,0], max[96,32]
//updatePixels[64,95, 300,269]
//image width/height=400,300
//min[96,0], max[128,32]
//updatePixels[96,127, 300,269]
//image width/height=400,300
//min[128,0], max[160,32]
//updatePixels[128,159, 300,269]
//image width/height=400,300
//min[96,96], max[128,128]
//updatePixels[96,127, 204,173]
//image width/height=400,300
//min[128,32], max[160,64]
//updatePixels[128,159, 268,237]
//image width/height=400,300
//min[160,32], max[192,64]
//updatePixels[160,191, 268,237]
//image width/height=400,300
//min[160,0], max[192,32]
//updatePixels[160,191, 300,269]
//image width/height=400,300
//min[192,0], max[224,32]
//updatePixels[192,223, 300,269]
//image width/height=400,300
//min[224,0], max[256,32]
//updatePixels[224,255, 300,269]
//image width/height=400,300
//min[224,32], max[256,64]
//updatePixels[224,255, 268,237]
//image width/height=400,300
//min[192,32], max[224,64]
//updatePixels[192,223, 268,237]
//image width/height=400,300
//min[192,64], max[224,96]
//updatePixels[192,223, 236,205]
//image width/height=400,300
//min[224,96], max[256,128]
//updatePixels[224,255, 204,173]
//image width/height=400,300
//min[224,64], max[256,96]
//updatePixels[224,255, 236,205]
//image width/height=400,300
//min[192,96], max[224,128]
//updatePixels[192,223, 204,173]
//image width/height=400,300
//min[160,64], max[192,96]
//updatePixels[160,191, 236,205]
//image width/height=400,300
//min[128,64], max[160,96]
//updatePixels[128,159, 236,205]
//image width/height=400,300
//min[160,96], max[192,128]
//updatePixels[160,191, 204,173]
//image width/height=400,300
//min[128,96], max[160,128]
//updatePixels[128,159, 204,173]
//image width/height=400,300
//min[128,128], max[160,160]
//updatePixels[128,159, 172,141]
//image width/height=400,300
//min[128,160], max[160,192]
//updatePixels[128,159, 140,109]
//image width/height=400,300
//min[160,160], max[192,192]
//updatePixels[160,191, 140,109]
//image width/height=400,300
//min[160,128], max[192,160]
//updatePixels[160,191, 172,141]
//image width/height=400,300
//min[224,128], max[256,160]
//updatePixels[224,255, 172,141]
//image width/height=400,300
//min[192,128], max[224,160]
//updatePixels[192,223, 172,141]
//image width/height=400,300
//min[224,160], max[256,192]
//updatePixels[224,255, 140,109]
//image width/height=400,300
//min[192,160], max[224,192]
//updatePixels[192,223, 140,109]
//image width/height=400,300
//min[192,192], max[224,224]
//updatePixels[192,223, 108,77]
//image width/height=400,300
//min[224,224], max[256,256]
//updatePixels[224,255, 76,45]
//image width/height=400,300
//min[224,192], max[256,224]
//updatePixels[224,255, 108,77]
//image width/height=400,300
//min[192,224], max[224,256]
//updatePixels[192,223, 76,45]
//image width/height=400,300
//min[160,224], max[192,256]
//updatePixels[160,191, 76,45]
//image width/height=400,300
//min[160,192], max[192,224]
//updatePixels[160,191, 108,77]
//image width/height=400,300
//min[128,192], max[160,224]
//updatePixels[128,159, 108,77]
//image width/height=400,300
//min[128,224], max[160,256]
//updatePixels[128,159, 76,45]
//image width/height=400,300
//min[96,224], max[128,256]
//updatePixels[96,127, 76,45]
//image width/height=400,300
//min[64,224], max[96,256]
//updatePixels[64,95, 76,45]
//image width/height=400,300
//min[64,192], max[96,224]
//updatePixels[64,95, 108,77]
//image width/height=400,300
//min[96,192], max[128,224]
//updatePixels[96,127, 108,77]
//image width/height=400,300
//min[96,160], max[128,192]
//updatePixels[96,127, 140,109]
//image width/height=400,300
//min[96,128], max[128,160]
//updatePixels[96,127, 172,141]
//image width/height=400,300
//min[64,128], max[96,160]
//updatePixels[64,95, 172,141]
//image width/height=400,300
//min[32,160], max[64,192]
//updatePixels[32,63, 140,109]
//image width/height=400,300
//min[32,128], max[64,160]
//updatePixels[32,63, 172,141]
//image width/height=400,300
//min[0,128], max[32,160]
//updatePixels[0,31, 172,141]
//image width/height=400,300
//min[0,160], max[32,192]
//updatePixels[0,31, 140,109]
//image width/height=400,300
//min[0,192], max[32,224]
//updatePixels[0,31, 108,77]
//image width/height=400,300
//min[64,160], max[96,192]
//updatePixels[64,95, 140,109]
//image width/height=400,300
//min[32,192], max[64,224]
//updatePixels[32,63, 108,77]
//image width/height=400,300
//min[32,224], max[64,256]
//updatePixels[32,63, 76,45]
//image width/height=400,300
//min[0,224], max[32,256]
//updatePixels[0,31, 76,45]
//image width/height=400,300
//min[0,108], max[32,120]
//updatePixels[0,31, 192,181]
//image width/height=400,300
//min[32,108], max[64,120]
//updatePixels[32,63, 192,181]
//image width/height=400,300
//min[0,256], max[32,288]
//updatePixels[0,31, 44,13]
//image width/height=400,300
//min[32,256], max[64,288]
//updatePixels[32,63, 44,13]
//image width/height=400,300
//min[64,256], max[96,288]
//updatePixels[64,95, 44,13]
//image width/height=400,300
//min[96,108], max[128,120]
//updatePixels[96,127, 192,181]
//image width/height=400,300
//min[64,108], max[96,120]
//updatePixels[64,95, 192,181]
//image width/height=400,300
//min[160,108], max[192,120]
//updatePixels[160,191, 192,181]
//image width/height=400,300
//min[128,108], max[160,120]
//updatePixels[128,159, 192,181]
//image width/height=400,300
//min[96,256], max[128,288]
//updatePixels[96,127, 44,13]
//image width/height=400,300
//min[128,256], max[160,288]
//updatePixels[128,159, 44,13]
//image width/height=400,300
//min[160,256], max[192,288]
//updatePixels[160,191, 44,13]
//image width/height=400,300
//min[192,108], max[224,120]
//updatePixels[192,223, 192,181]
//image width/height=400,300
//min[224,108], max[256,120]
//updatePixels[224,255, 192,181]
//image width/height=400,300
//min[192,256], max[224,288]
//updatePixels[192,223, 44,13]
//image width/height=400,300
//min[224,256], max[256,288]
//updatePixels[224,255, 44,13]
//image width/height=400,300
//min[256,256], max[288,288]
//updatePixels[256,287, 44,13]
//image width/height=400,300
//min[256,108], max[288,120]
//updatePixels[256,287, 192,181]
//image width/height=400,300
//min[288,108], max[320,120]
//updatePixels[288,319, 192,181]
//image width/height=400,300
//min[320,256], max[352,288]
//updatePixels[320,351, 44,13]
//image width/height=400,300
//min[352,256], max[384,288]
//updatePixels[352,383, 44,13]
//image width/height=400,300
//min[352,108], max[384,120]
//updatePixels[352,383, 192,181]
//image width/height=400,300
//min[320,108], max[352,120]
//updatePixels[320,351, 192,181]
//image width/height=400,300
//min[192,108], max[208,120]
//updatePixels[192,207, 192,181]
//image width/height=400,300
//min[192,256], max[208,288]
//updatePixels[192,207, 44,13]
//image width/height=400,300
//min[192,128], max[208,160]
//updatePixels[192,207, 172,141]
//image width/height=400,300
//min[192,160], max[208,192]
//updatePixels[192,207, 140,109]
//image width/height=400,300
//min[192,192], max[208,224]
//updatePixels[192,207, 108,77]
//image width/height=400,300
//min[192,224], max[208,256]
//updatePixels[192,207, 76,45]
//image width/height=400,300
//min[288,256], max[320,288]
//updatePixels[288,319, 44,13]
//image width/height=400,300
//min[352,224], max[384,256]
//updatePixels[352,383, 76,45]
//image width/height=400,300
//min[352,192], max[384,224]
//updatePixels[352,383, 108,77]
//image width/height=400,300
//min[320,192], max[352,224]
//updatePixels[320,351, 108,77]
//image width/height=400,300
//min[320,224], max[352,256]
//updatePixels[320,351, 76,45]
//image width/height=400,300
//min[288,224], max[320,256]
//updatePixels[288,319, 76,45]
//image width/height=400,300
//min[256,224], max[288,256]
//updatePixels[256,287, 76,45]
//image width/height=400,300
//min[256,192], max[288,224]
//updatePixels[256,287, 108,77]
//image width/height=400,300
//min[288,192], max[320,224]
//updatePixels[288,319, 108,77]
//image width/height=400,300
//min[288,160], max[320,192]
//updatePixels[288,319, 140,109]
//image width/height=400,300
//min[256,128], max[288,160]
//updatePixels[256,287, 172,141]
//image width/height=400,300
//min[288,128], max[320,160]
//updatePixels[288,319, 172,141]
//image width/height=400,300
//min[320,128], max[352,160]
//updatePixels[320,351, 172,141]
//image width/height=400,300
//min[256,160], max[288,192]
//updatePixels[256,287, 140,109]
//image width/height=400,300
//min[320,160], max[352,192]
//updatePixels[320,351, 140,109]
//image width/height=400,300
//min[352,160], max[384,192]
//updatePixels[352,383, 140,109]
//image width/height=400,300
//min[352,128], max[384,160]
//updatePixels[352,383, 172,141]
//image width/height=400,300
//min[352,96], max[384,128]
//updatePixels[352,383, 204,173]
//image width/height=400,300
//min[352,64], max[384,96]
//updatePixels[352,383, 236,205]
//image width/height=400,300
//min[320,64], max[352,96]
//updatePixels[320,351, 236,205]
//image width/height=400,300
//min[320,96], max[352,128]
//updatePixels[320,351, 204,173]
//image width/height=400,300
//min[288,96], max[320,128]
//updatePixels[288,319, 204,173]
//image width/height=400,300
//min[256,96], max[288,128]
//updatePixels[256,287, 204,173]
//image width/height=400,300
//min[256,64], max[288,96]
//updatePixels[256,287, 236,205]
//image width/height=400,300
//min[288,64], max[320,96]
//updatePixels[288,319, 236,205]
//image width/height=400,300
//min[288,32], max[320,64]
//updatePixels[288,319, 268,237]
//image width/height=400,300
//min[256,32], max[288,64]
//updatePixels[256,287, 268,237]
//image width/height=400,300
//min[256,0], max[288,32]
//updatePixels[256,287, 300,269]
//image width/height=400,300
//min[288,0], max[320,32]
//updatePixels[288,319, 300,269]
//image width/height=400,300
//min[320,0], max[352,32]
//updatePixels[320,351, 300,269]
//image width/height=400,300
//min[320,32], max[352,64]
//updatePixels[320,351, 268,237]
//image width/height=400,300
//min[352,32], max[384,64]
//updatePixels[352,383, 268,237]
//image width/height=400,300
//min[352,0], max[384,32]
//updatePixels[352,383, 300,269]
//image width/height=400,300
//min[192,0], max[208,32]
//updatePixels[192,207, 300,269]
//image width/height=400,300
//min[192,32], max[208,64]
//updatePixels[192,207, 268,237]
//image width/height=400,300
//min[192,64], max[208,96]
//updatePixels[192,207, 236,205]
//image width/height=400,300
//min[192,96], max[208,128]
//updatePixels[192,207, 204,173]
