//### SCENE BEGIN ###
//    Generated by Liquid v2.3.5 (buildtime=23:36:11.35)
//    Scene : E:/MyDocuments/maya/projects/default/test_liqShaderNode_surface_as_lambertFastsssSS
//    User  : yaoyansi
//    Time  : Sun Aug 26 23:55:23 2012


//############################### option #
// maya settings: focal=35, aperture = 36, aspect=1.33333
//Depth of Field on camera "|persp|perspShape" is turned off in Maya

//############################### camera #
//----------------------------------camera instance: currentJob.camera[0].name
ei_shader("liquidShader7");
//the type of node 'liquidShader7' is not implemented yet. And don't forget to add the valid connections of this type to ShaderValidConnection::setValidConnection()
ei_end_shader();

ei_material("liquidShader7SG");
ei_add_surface("liquidShader7");
ei_end_material();

//worldPrologue

// Renderer::exportLight("_pointLight1_pointLightShape1");

// Renderer::exportPointLight()

// Renderer::exportOneGeometry_Mesh(|pPlane1|pPlaneShape1,0,0)

//############################### mesh #
//shape full path name=|pPlane1|pPlaneShape1

// Renderer::exportOneGeometry_Mesh(|pCube1|pCubeShape1,0,0)

//############################### mesh #
//shape full path name=|pCube1|pCubeShape1
//--------------------------
//ribNode->name=|pPlane1|pPlaneShape1
//ribNode's transform node=|pPlane1
//ribNode->object(0)->getDataPtr()->getFullPathName()=|pPlane1|pPlaneShape1
//shape name=|pPlane1|pPlaneShape1
//shape full path name=|pPlane1|pPlaneShape1
//ribNode->doDef=205, ribNode->doMotion=205
{//light group(light-link group)
//
//--------------------------
//ribNode->name=|pCube1|pCubeShape1
//ribNode's transform node=|pCube1
//ribNode->object(0)->getDataPtr()->getFullPathName()=|pCube1|pCubeShape1
//shape name=|pCube1|pCubeShape1
//shape full path name=|pCube1|pCubeShape1
//ribNode->doDef=205, ribNode->doMotion=205
{//light group(light-link group)
//

//Renderer::worldEpilogue()
//image width/height=768,576
//min[0,0], max[32,32]
//updatePixels[0,31, 576,545]
//image width/height=768,576
//min[0,32], max[32,64]
//updatePixels[0,31, 544,513]
//image width/height=768,576
//min[32,32], max[64,64]
//updatePixels[32,63, 544,513]
//image width/height=768,576
//min[64,0], max[96,32]
//updatePixels[64,95, 576,545]
//image width/height=768,576
//min[32,0], max[64,32]
//updatePixels[32,63, 576,545]
//image width/height=768,576
//min[96,0], max[128,32]
//updatePixels[96,127, 576,545]
//image width/height=768,576
//min[96,32], max[128,64]
//updatePixels[96,127, 544,513]
//image width/height=768,576
//min[64,32], max[96,64]
//updatePixels[64,95, 544,513]
//image width/height=768,576
//min[64,64], max[96,96]
//updatePixels[64,95, 512,481]
//image width/height=768,576
//min[96,64], max[128,96]
//updatePixels[96,127, 512,481]
//image width/height=768,576
//min[96,96], max[128,128]
//updatePixels[96,127, 480,449]
//image width/height=768,576
//min[64,96], max[96,128]
//updatePixels[64,95, 480,449]
//image width/height=768,576
//min[32,96], max[64,128]
//updatePixels[32,63, 480,449]
//image width/height=768,576
//min[32,64], max[64,96]
//updatePixels[32,63, 512,481]
//image width/height=768,576
//min[0,64], max[32,96]
//updatePixels[0,31, 512,481]
//image width/height=768,576
//min[0,96], max[32,128]
//updatePixels[0,31, 480,449]
//image width/height=768,576
//min[0,128], max[32,160]
//updatePixels[0,31, 448,417]
//image width/height=768,576
//min[32,128], max[64,160]
//updatePixels[32,63, 448,417]
//image width/height=768,576
//min[32,160], max[64,192]
//updatePixels[32,63, 416,385]
//image width/height=768,576
//min[0,160], max[32,192]
//updatePixels[0,31, 416,385]
//image width/height=768,576
//min[0,192], max[32,224]
//updatePixels[0,31, 384,353]
//image width/height=768,576
//min[0,224], max[32,256]
//updatePixels[0,31, 352,321]
