print "This is $ER_SHADER_USER/src/er_checker2/userSetup.mel\n";

string $erSHADER_user_DIR = getenv("ER_SHADER_USER");
if( $erSHADER_user_DIR == "" )
{
    error("environment variable <ER_SHADER_USER> is not set in Maya.env");
} else {
    eval( "source \"" + $erSHADER_user_DIR + "/src/er_checker2/AEer_checker2Template.mel\"" );
}
//
global proc int liquidAssignUserShaderToSelected_elvishray_er_checker2(string $node)
{
	liqPushIdent();	
	liqAElog("liquidAssignUserShaderToSelected_elvishray_er_checker2("+$node+")");
	


	liqPopIdent();
	return 1;
}