source xxliquidutility.mel;

//
global proc liqMDGMessage_addNodeAddedCallback_renderman(string $node)
{
	liqPushIdent();
	liqlog("liqMDGMessage_addNodeAddedCallback_renderman("+$node+")");

	string $type = `nodeType $node`;
	
	if($type == "pointLight")
	{
		rmAddAttribute_pointlight($node);
	}
	else if($type == "transform"){
		rmAddAttribute_transform($node);
	}
	else{
		liqlog("$type=["+$type+"] is not supported.");
	}

	liqPopIdent();
}
