source xxliquidutility.mel;

global proc AEliquidShaderTemplate_luxrenderer(string $node, string $attr)
{
	liqPushIdent();
	liqAElog("AEliquidShaderTemplate_luxrenderer("+$node+","+$attr+")");

	//editorTemplate -beginLayout "luxrenderer";
		//--------------------------------------------------
		//--------------------------------------------------
		//--------------------------------------------------
		//--------------------------------------------------
	//editorTemplate -endLayout;

	liqPopIdent();
}