print "This is $RM_SHADER_USER/src/rmFlat/userSetup.mel\n";

string $rmSHADER_user_DIR = getenv("RM_SHADER_USER");
if( $rmSHADER_user_DIR == "" )
{
    error("environment variable <RM_SHADER_USER> is not set in Maya.env");
} else {
    eval( "source \"" + $rmSHADER_user_DIR + "/src/rmFlat/AErmFlatTemplate.mel\"" );
}
//
global proc int liquidAssignUserShaderToSelected_renderman_rmFlat(string $node)
{
	liqPushIdent();	
	liqAElog("liquidAssignUserShaderToSelected_elvishray_rmFlat("+$node+")");
	


	liqPopIdent();
	return 1;
}
//
global proc liquidBuildHypergraphNodePopupMenuItems_rmFlat( string $node )
{
	liqPushIdent();
	liqlog("liquidBuildHypergraphNodePopupMenuItems_rmFlat("+$node+")");
	liqPopIdent();
}