
print "This is elvishray /2.3.3/src/elvishray/mel/usersetup.mel.\n";

source er_AEliquidInstanceFlags.mel;
source er_CreateMenus.mel;
source AEliquidShaderTemplate_elvishray.mel;
source er_callback.mel;
source er_UserCallbackInterface.mel;
source er_startup.mel;
source AEelvishrayGlobalsTemplate.mel;
source AEelvishrayGlobalsTemplate.res.mel;
source AEer_physicalskyTemplate.mel;
source er_CameraVisibility.mel;
