source xxliquidutility.mel;

global proc AEliquidShaderTemplate_appleseed(string $node, string $attr)
{
	liqPushIdent();
	liqAElog("AEliquidShaderTemplate_appleseed("+$node+","+$attr+")");

	//editorTemplate -beginLayout "appleseed";
		//--------------------------------------------------
		//--------------------------------------------------
		//--------------------------------------------------
		//--------------------------------------------------
	//editorTemplate -endLayout;

	liqPopIdent();
}