source xxliquidutility.mel;

//
global proc AEliquidInstanceFlags_appleseed( string $node )
{
	liqPushIdent();
	liqlog("AEliquidInstanceFlags_appleseed("+$node+")");

	editorTemplate -beginLayout "appleseed" -collapse true;
		editorTemplate -label "as_testattr0"    -addDynamicControl "as_testattr0";
		editorTemplate -label "as_testattr1"    -addDynamicControl "as_testattr1";
	editorTemplate -endLayout;

	liqPopIdent();
}