source xxliquidutility.mel;

global proc liquidAssignShaderToSelected_ElvishRender(string $node)
{
	liqPushIdent();
	liqlog("liquidAssignShaderToSelected_ElvishRender("+$node+")");
	
	liquidAssignShaderToSelected_elvishray($node);

	liqPopIdent();
}
//
global proc liqHyperShadeCreateMenu_BuildMenu_ElvishRender()
{
	liqPushIdent();
	liqlog("liqHyperShadeCreateMenu_BuildMenu_ElvishRender()");
	
	liqHyperShadeCreateMenu_BuildMenu_elvishray();

	liqPopIdent();
}
//
global proc string[] liqExcludeClassficationNodes_ElvishRender(string $classification, string $exclude[])
{
	liqPushIdent();
	liqlog("liqExcludeClassficationNodes_ElvishRender("+$classification+", $exclude[])");
	
	$exclude = liqExcludeClassficationNodes_elvishray($classification, $exclude);

	liqPopIdent();
	return $exclude;
}
//
global proc liqRenderNode_CreateTreeLister_Content_ElvishRender(string $renderNodeTreeLister, string $postCommand, string $filterClassArray[])
{
	liqPushIdent();
	liqlog("liqRenderNode_CreateTreeLister_Content_ElvishRender("+$renderNodeTreeLister+","+$postCommand+", ["+stringArrayToString($filterClassArray,",")+"])");
	liqRenderNode_CreateTreeLister_Content_elvishray($renderNodeTreeLister, $postCommand, $filterClassArray);
	liqPopIdent();
	return;
}
//
global proc int LIQUID_isLiquidClassification_ElvishRender(string $classification)
{
	liqPushIdent();
	liqlog("LIQUID_isLiquidClassification_ElvishRender("+$classification+")");
	int $ret;
	$ret = LIQUID_isLiquidClassification_elvishray($classification);
	liqPopIdent();
	return $ret;
}
//
global proc string LIQUID_getCreateBarItemCallbackCmd_ElvishRender(
	string $classification,
	string $as,
	string $postCommand,
	string $type)
{
	liqPushIdent();
	liqlog("LIQUID_getCreateBarItemCallbackCmd_ElvishRender("+$classification+","+$as+","+$postCommand+","+$type+")");
	
	string $ret;
	$ret = LIQUID_getCreateBarItemCallbackCmd_elvishray($classification, $as, $postCommand, $type);
	
	liqPopIdent();
	return $ret;
}
