source xxliquidutility.mel;

global proc liquidAssignShaderToSelected_ElvishRender(string $node)
{
	liqPushIdent();
	liqlog("liquidAssignShaderToSelected_ElvishRender("+$node+")");
	
	liquidAssignShaderToSelected_elvishray($node);

	liqPopIdent();
}
//
global proc liqHyperShadeCreateMenu_BuildMenu_ElvishRender()
{
	liqPushIdent();
	liqlog("liqHyperShadeCreateMenu_BuildMenu_ElvishRender()");
	
	liqHyperShadeCreateMenu_BuildMenu_elvishray();

	liqPopIdent();
}